#!/usr/bin/env python3
"""Rebuild reference/page_index.json from the portal.

Every id list in this project used to be scraped out of CONVERSION_INDEX.md with
a bare \\b21[0-9]{10}\\b regex. That file names both the V1 record and the V3 build
for each page, so the regex quietly returned a mix of the two, and counts run
against it attributed copy on throwaway -v3 duplicates to the real site. Ask the
portal instead: the template tells you it is a Private Label page and the slug
tells you whether it is the real one.

usage: page_index.py            (TOKEN in env)
"""
import json, os, urllib.request

TOK = os.environ['TOKEN']
H   = {"Authorization": "Bearer " + TOK}
S   = os.path.dirname(os.path.abspath(__file__)) + '/'
SCRATCH = {'private-label-test', 'pl-module-library'}


def get(u):
    return json.load(urllib.request.urlopen(
        urllib.request.Request("https://api.hubapi.com" + u, headers=H)))


def bucket(slug):
    # -v1ref pages are read-only replicas of the pre-conversion look, built so a
    # reviewer could see "before" beside "after". They render like the real site
    # and were bucketed as production once, which inflated every phrase count.
    if slug.endswith('-v1ref'): return 'reference'
    if slug.endswith('-v3'):    return 'duplicate'
    if slug in SCRATCH:         return 'scratch'
    return 'production'


def main():
    pages, off = [], 0
    while True:
        r = get(f"/cms/v3/pages/site-pages?limit=100&offset={off}"
                "&property=id,name,slug,templatePath")
        res = r.get('results', [])
        if not res:
            break
        pages += [p for p in res if 'Private Label' in (p.get('templatePath') or '')]
        off += 100
        if off > 1400:
            break

    out = {'_note': 'Generated by tools/page_index.py. Do not hand-edit.',
           'production': [], 'duplicate': [], 'reference': [], 'scratch': []}
    for p in sorted(pages, key=lambda x: x.get('slug') or ''):
        out[bucket(p.get('slug') or '')].append(
            {'id': p['id'], 'slug': p.get('slug'), 'name': p.get('name')})

    json.dump(out, open(S + '../reference/page_index.json', 'w'), indent=1)
    for k in ('production', 'duplicate', 'reference', 'scratch'):
        print(f"  {k:11} {len(out[k])}")


main()
